version: '3.8'
services:
  spark-master:
    container_name: spark-master
    deploy:
        resources:
            limits:
              cpus: '1'
              memory: "2g"
    image: veribilimiokulu/pyspark-3.4.1_python-3.8:1.0
    ports:
      - "4040:4040"
      - "7077:7077"
      - "8080:8080"
      - "18080:18080"
    networks:
      - vbo
    command: sh spark-master.sh

  spark-worker:
    deploy:
        resources:
            limits:
              cpus: '1'
              memory: "2g"
    image: veribilimiokulu/pyspark-3.4.1_python-3.8:1.0
    depends_on:
      - spark-master
    ports:
      - "8081-8089:8081"
    networks:
      - vbo
    command: sh spark-worker.sh

  spark-client:
    container_name: spark-client
    deploy:
        resources:
            limits:
              cpus: '1'
              memory: "2g"
    build: spark_client
    ports:
      - "8888:8888"
      - "4041:4040"
    networks:
      - vbo
    volumes:
      - ./spark_client/examples:/opt/examples
    command: sleep infinity

# S3 compatible object storage: MinIO
  minio:
    container_name: minio-sinem
    image: "minio/minio:RELEASE.2023-05-04T21-44-30Z"
    volumes:
      - minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - vbo
    environment:
      MINIO_ACCESS_KEY: "dataops"
      MINIO_SECRET_KEY: "Ankara06"
    command: server /data --console-address ":9001"
    
  zookeeper:
    image: quay.io/debezium/zookeeper:2.1
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    networks:
      - vbo

  kafka:
    container_name: kafka
    image: quay.io/debezium/kafka:2.1
    ports:
     - 9092:9092
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - vbo

  postgres:
    container_name: postgres
    image: quay.io/debezium/example-postgres:2.1
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - vbo

  connect:
    container_name: connect
    image: quay.io/debezium/connect:2.1
    ports:
     - 8083:8083
    depends_on:
     - kafka
     - postgres
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
    networks:
      - vbo

volumes:
  minio:
  postgres-db-volume:

networks:
  vbo: 